name: Run Quant Scholar
on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
  workflow_dispatch:
  schedule:
    # Every day at 00:00
    - cron: "0 0 */1 * *"
env:
  GITHUB_USER_NAME: WinstonLiyte
  GITHUB_USER_EMAIL: 1957922024@qq.com

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - name: Set up Python Env
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install arxiv requests pyyaml

      - name: Run quant_scholar.py
        run: |
          python quant_scholar.py
          cp docs/papers.md wiki/index.md

      - name: Commit and Push
        run: |
          git config --global user.name "${{ env.GITHUB_USER_NAME }}"
          git config --global user.email "${{ env.GITHUB_USER_EMAIL }}"
          git add docs/papers.md docs/quant-scholar.json wiki/index.md
          git commit -m "[Workflow] Automatic Update Quant Scholar Paper List" || echo "No changes to commit"
          git push
