name: Run Quant Scholar

on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string

  workflow_dispatch:
  schedule:
    - cron: "0 0 */1 * *"


env:
  GITHUB_USER_NAME: WinstonLiyte
  GITHUB_USER_EMAIL: 1957922024@qq.com
  
  
jobs:
  build:
    name: update
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Set up Python Env
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install arxiv
          pip install requests
          pip install pyyaml
          
      - name: Run quant_scholar.py
        run: |
            python quant_scholar.py
            cp README.md wiki/index.md
          
      - name: Push update the quant scholar paper list
        uses: github-actions-x/commit@v2.9
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "[Workflow] Automatic Update Quant Scholar Paper List"
          files: README.md docs/quant-scholar.json wiki/index.md
          rebase: 'true'
          name: ${{ env.GITHUB_USER_NAME }}
          email: ${{ env.GITHUB_USER_EMAIL }}
