# Sample configuration file for crawlers

# General settings
output_dir: "data"
max_results: 20
download_pdf: true

# API tokens (optional)
github_token: ""  # Add your GitHub token here for higher rate limits

# Keywords for searching
keywords:
  "Machine Learning in Finance":
    filters:
      - "Machine Learning in Finance"
      - "Statistical Finance"
  
  "Deep Learning in Finance":
    filters:  
      - "Deep Learning in Finance"
      - "Computational Engineering, Finance, and Science"
  
  "Reinforcement Learning in Finance":
    filters:
      - "Reinforcement Learning in Finance"
  
  "Time Series Forecasting":
    filters:
      - "Time Series Forecasting"
